[project]
name = "kakeibo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "pyzaim>=1.1.0",
    "requests-oauthlib>=2.0.0",
    "python-dotenv>=1.0.0",
    "openpyxl>=3.1.0",
    "matplotlib>=3.9.0",
    "plotly>=5.0.0",
]
